version: '3.1'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password 
    ports:
      - 27017:27017
    volumes:
      - mongo_data_container:/data/db

volumes:
  mongo_data_container: