version: '3'

services:
  db:
    image: 'cockroachdb/cockroach:v22.1.1'
    command: start-single-node --insecure
    ports:
      - 26257:26257
      - 5050:8080
    networks:
      - app_network
    restart: unless-stopped

  supertokens:
    image: us-central1-docker.pkg.dev/ethans-playground-350400/supertokens-forks/supertokens-postgresql
    depends_on:
      - db
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: 'postgresql://root@db:26257/defaultdb'
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
